In [1]:
import matplotlib.pyplot as plt

import pickle
import numpy as np

In [2]:
with open('sensitive_analysis_9v_100.pkl','r') as inputs:
    data= pickle.load(inputs)
with open('sensitive_analysis_base_renewal.pkl','r') as inputsbase:
    data_base = pickle.load(inputsbase)

In [3]:
data[0]

([0, 0.0, 0.0, 0.0, 19.477, 0.0, 464.927],
 [[2.81, 4.63, 6.1], [0.6, 0.63, 0.67], [-0.25, -0.5, -0.8845498235179737]],
 array([ 0.83339259,  0.98069781,  0.84402627,  1.27182613,  1.02684928,
         1.03964157,  0.90736933,  1.11858214,  1.08324004,  1.18013141,
         1.14967592,  1.20614125,  1.16208183,  1.20560844,  0.92224523,
         1.03058424,  0.99652524,  1.03183546,  0.99010228,  1.03558327,
         1.00513466,  1.05345246,  1.0220686 ,  1.0405148 ,  1.00509389,
         1.05394844,  1.01817047,  1.06700707,  1.03295254,  1.31407542,
         1.19432648,  0.94356203,  0.92529425,  0.96486526,  0.94042373,
         0.96090634,  0.93639369,  0.97642025,  0.95157668,  0.95819144,
         0.93330666,  0.97191128,  0.943138  ,  0.97222063,  0.94462574,
         0.98841155,  0.88343373,  0.95482889,  0.93013367,  0.96837803,
         0.94915521,  0.96387682,  0.94315145,  0.98278954,  0.88423962,
         0.96068415,  0.93946215,  0.9765367 ,  0.89206778,  0.99608591,
    

In [6]:
data[3]

([0, 0.0, 0.0, 0.0, 17.908, 0.0, 444.639],
 [[2.81, 4.63, 6.1], [0.6, 0.63, 0.67], [-0.25, -0.5, -0.9026618876875466]],
 array([ 0.83164041,  0.9841929 ,  0.84325011,  1.27950079,  1.02573756,
         1.03816967,  0.90870179,  1.11703266,  1.0895584 ,  1.17808651,
         1.14490599,  1.2025475 ,  1.16257051,  1.20659197,  0.92493805,
         1.02372337,  0.98581051,  1.02120007,  0.98396186,  1.03187058,
         0.99687471,  1.04212967,  1.00753031,  1.04311421,  1.00953462,
         1.05091653,  1.01561225,  1.06701581,  1.03083672,  1.30877666,
         1.1723557 ,  0.9426852 ,  0.92439662,  0.96161414,  0.93787309,
         0.96086146,  0.93545236,  0.97206446,  0.94532862,  0.95564852,
         0.93153809,  0.96789867,  0.94834761,  0.96263391,  0.94250766,
         0.98446554,  0.87888664,  0.95857951,  0.93498567,  0.97764775,
         0.94677336,  0.96375647,  0.94243424,  0.98331594,  0.88524244,
         0.9632425 ,  0.94268725,  0.98392157,  0.89372363,  0.9998511 ,
    

In [4]:
# -- coding utf-8 --

#Created on Fri Jun 16 151644 2017
#@author Ted Yang


import datetime as dt
from tree import TreeModel
from bau import DLWBusinessAsUsual
from cost import DLWCost
from damage import DLWDamage
from utility import EZUtility
from optimization import GeneticAlgorithm, GradientSearch
import numpy as np
class matlabmode():
    def __init__(self):
        '''init the class with default settings:
        1. decision time is set to [0, 15, 45, 85, 185, 285, 385]
        2. cost is using default x60 = 0.543, x100 = 0.671 and euro to dollar exchange rate = 1.2
        3. In the back stop tech model, join price is set to 2000, max prive is set to 2500, phi_0 = 1.5, phi_1 = 0 and constant = 30460
        3. constant growth of consumption is set to 0.015, subinterval length is 5 and ghg levels are 450,650,1000.
        4. Draws of simulation  = 4000000
        5. Disaster model's set up is  peak_temperature=6.0, disaster_tail=18.0. 
        6. Damage is simulated by pindcyk method with time to hit the max temperature = 100
        7. In utility, the parameter rho from the DLW-paper is set to 1-1/0.9, alpha is set to -6 and beta is set to 0.995^5 '''

        t = TreeModel(decision_times=[0, 15, 45, 85, 185, 285, 385])
        bau_default_model = DLWBusinessAsUsual()
        bau_default_model.bau_emissions_setup(tree=t)
        c = DLWCost(t, bau_default_model.emit_level[0], g=92.08, a=3.413, join_price=2000.0, max_price=2500.0,
                        tech_const=1.5, tech_scale=0.0, cons_at_0=30460.0)
        df = DLWDamage(tree=t, bau=bau_default_model, cons_growth=0.015, ghg_levels=[450, 650, 1000], subinterval_len=5)    
        df.damage_simulation(draws=4000000, peak_temp=6.0, disaster_tail=18.0, tip_on=True, 
                                 temp_map=0, temp_dist_params=None, maxh=100.0)
        u = EZUtility(tree=t, damage=df, cost=c, period_len=5.0, eis=0.9, ra=7.0, time_pref=0.005)
        self.u = u

    def get_start_point(self):
        #use GA to get the start point for local optimizer
        ga_model = GeneticAlgorithm(pop_amount=150, num_generations=1, cx_prob=0.8, mut_prob=0.5, 
                              bound=1.5, num_feature=63, utility=self.u, print_progress=True) 
        final_pop, fitness = ga_model.run()
        sort_pop = final_pop[np.argsort(fitness)][::-1]
        begin_pop = final_pop[np.argsort(fitness)][-1]
        return sort_pop,begin_pop

    def utility_grad(self,m):
        #use finite differenciation to gradient and utility
        m = np.array(m)
        gs_model = GradientSearch(var_nums=63, utility=self.u, accuracy=1e-8, 
                              iterations=1, print_progress=True)
        grad = gs_model.numerical_gradient(m)
        return self.u.utility(m),grad

    def grad(self,m):
        #use finite differenciation to gradient and utility
        m = np.array(m)
        gs_model = GradientSearch(var_nums=63, utility=self.u, accuracy=1e-8, 
                              iterations=1, print_progress=True)
        grad = gs_model.numerical_gradient(m)
        return grad

    def utility(self,m):
        # get utility from utlity class
        m = np.array(m)
        #result_array=np.array([])
        # if m.ndim ==1:
        return self.u.utility(m)
            
        # else:
        #     row= 10
        #     for row_index in range(row):
        #         result_array= np.append(result_array,self.u.utility(m[row_index,:]))
        #     return result_array
    def GS(self,m):
    	#m = np.array(m)
        gs_model = GradientSearch(var_nums=63, utility=self.u, accuracy=1e-8, 
                              iterations=1, print_progress=True)
    	m_opt, u_opt = gs_model.run(initial_point_list=m, topk=1)
    	return m_opt,u_opt

def get_start(y):
    return y.get_start_point()

def get_u_g(m,y):
    return y.utility_grad(m)

def get_u(m,y):
    return y.utility(m)

def get_g(m,y):
    return y.grad(m)
    
def call_gs(m,y):
	return y.GS(m)

In [5]:
y = matlabmode()

Starting damage simulation..
Done!


In [6]:
x1 = y.get_start_point()[0]

----------------Genetic Evolution Starting----------------
-- Generation 1 --
 Min 3.35607767826e-15 
 Max 8.55134629682 
 Avg 7.39517060877
 Std 2.2013072536 
 Population Size 150
 Best Individual:  [ 0.85636267  1.08859521  1.09360196  0.68851739  1.43744154  0.26646038
  0.55788051  1.16521025  0.32861535  0.21658191  0.87448126  0.52459373
  0.51403673  0.95690903  0.65488361  1.01638218  0.68795922  1.37554654
  1.11105053  0.41189844  1.16018619  0.04884516  0.97668773  1.08767812
  0.28296206  1.34701726  0.98423544  0.48751363  0.88106791  0.4895983
  1.23397963  0.85392363  1.19602634  0.09020346  0.775204    1.1161146
  1.07979812  1.007442    1.4113279   0.72667251  1.42995766  1.45156783
  0.45299493  0.05954894  0.46133719  1.17648982  0.31310729  0.4837061
  1.04905967  0.92308716  1.15795716  0.69303871  0.86032862  0.8860074
  1.20969554  0.50795306  0.41058159  0.28117515  0.81849397  1.46412066
  0.30755213  0.54505347  0.3458119 ]


In [ ]:
x = get_g(data_base[0][1],y)

In [8]:
gs_model = GradientSearch(var_nums=63, utility=y.u, accuracy=1e-8, 
                      iterations=1, print_progress=True)

In [10]:
y.GS(x1)

----------------Gradient Search Starting----------------
Starting process 1 of Gradient Descent
-- Iteration 1 -- 
 Current Utility: 8.67462237354
[ 0.88723083  1.13260687  1.00849216  0.70608165  1.37453865  0.34545208
  0.59154862  1.17079882  0.44935561  0.35507893  0.92308466  0.5909344
  0.53102939  0.97015276  0.65523253  1.11632077  0.7586037   1.42124087
  1.11502082  0.45593677  1.17226848  0.06491383  0.97185119  1.11192001
  0.2859927   1.35172843  0.98429726  0.49968544  0.8845851   0.49168796
  1.2329735   0.93222625  1.16503625  0.10022462  0.77916043  1.13293075
  1.08137779  1.00884115  1.41170947  0.73629346  1.43108103  1.45520132
  0.4536139   0.06200777  0.46196189  1.16882262  0.31336842  0.49284798
  1.05000732  0.92367283  1.15801898  0.69555936  0.86079545  0.88631568
  1.2097451   0.51051768  0.41104602  0.28203326  0.81873884  1.46460534
  0.30760822  0.54529674  0.34581031]


(array([ 0.88723083,  1.13260687,  1.00849216,  0.70608165,  1.37453865,
         0.34545208,  0.59154862,  1.17079882,  0.44935561,  0.35507893,
         0.92308466,  0.5909344 ,  0.53102939,  0.97015276,  0.65523253,
         1.11632077,  0.7586037 ,  1.42124087,  1.11502082,  0.45593677,
         1.17226848,  0.06491383,  0.97185119,  1.11192001,  0.2859927 ,
         1.35172843,  0.98429726,  0.49968544,  0.8845851 ,  0.49168796,
         1.2329735 ,  0.93222625,  1.16503625,  0.10022462,  0.77916043,
         1.13293075,  1.08137779,  1.00884115,  1.41170947,  0.73629346,
         1.43108103,  1.45520132,  0.4536139 ,  0.06200777,  0.46196189,
         1.16882262,  0.31336842,  0.49284798,  1.05000732,  0.92367283,
         1.15801898,  0.69555936,  0.86079545,  0.88631568,  1.2097451 ,
         0.51051768,  0.41104602,  0.28203326,  0.81873884,  1.46460534,
         0.30760822,  0.54529674,  0.34581031]), 8.6746223735438992)

In [ ]:
m_t ='0.903879483936320	0.363429068455808	0.573327240626552	0.0850219497695642	0.127874993703247	0.151525814276405	0.986035915775205	0.441265495420156	0.253154179460103	0.259564792863577	0.208161562363009	0.970540857097490	0.238359398568151	0.499152902151700	0.103887581572938	0.658739874492949	0.324901334269585	0.451424347985208	0.710026998770444	0.456196085863435	0.684419923385944	0.332973836377714	0.586519259498864	0.465674496830032	0.0815914315352912	0.538194558630774	0.436857638848319	0.278769651601049	0.671906328164850	0.740574089171126	0.263478154559095	0.942635530215477	0.356542711325427	0.488581908426025	0.800536830135403	1.00022306144958	0.585262881612693	0.484230928649010	0.502892700949846	1.01978165009667	0.356470822280127	0.415975369598411	0.307999109033091	0.500391313498943	0.596831059714939	0.275277760971193	0.544947252465684	1.23307277447374	0.399846165964901	0.312025859552821	0.450329423966375	0.684139523296810	0.583741012653225	0.687064299034125	0.725676286975953	0.672343227494014	0.719600490885657	0.544693552923714	0.340558030615798	0.236754044020643	0.690846411134270	0.721410828755815	0.991257284346195'

In [ ]:
list1=m_t.split('\t')

In [ ]:
len(list1)

In [ ]:
np.linalg.norm(list1)

In [ ]:
data_base[0][1]

In [ ]:
def get_price_stat_ave(data,decision_times): #period average for each sample
    mitigation = []
    utility = []
    price = []
    a650 = []
    from tree import TreeModel 
    for i in range(len(data)): #load corresponding results
        mitigation.append(data[i][-3])
        utility.append(data[i][-2])
        price.append(data[i][-1])
        #a650.append(data[i][2])
    #print(np.mean(a650))
    
    t = TreeModel(decision_times)
    nodes_index = []
    for i in range(t.num_periods):
        nodes_index.append(t.get_nodes_in_period(i)) #get nodes for slicing
    price_stat_ave = np.zeros((len(data), t.num_periods))
    for i in range(len(data)):
        for j in range(t.num_periods):
            price_stat_ave[i,j] = np.average(data[i][-1][nodes_index[j][0]:nodes_index[j][1]+1])
    return price_stat_ave

def get_90_quantile(price_stat_ave):
    list0 = price_stat_ave[:,0]
    list1 = price_stat_ave[:,1]
    list2 = price_stat_ave[:,2]
    list3 = price_stat_ave[:,3]
    list4 = price_stat_ave[:,4]
    list5 = price_stat_ave[:,5]
    list_ = [list0,list1,list2,list3,list4,list5]
    fivepercent = int(len(list0)*0.05)
    for i in range(len(list_)):
        list_[i]=np.sort(list_[i])[fivepercent:-fivepercent] #take the 90% of the sorted results
    list_min = []
    list_max = []
    for i in list_:
        list_min.append(i[0])
        list_max.append(i[-1])   
    return list_min,list_max #take the lower and upper bounds for the test results

In [ ]:
decision_times=[0, 15, 45, 85, 185, 285, 385]
price_stat_ave= get_price_stat_ave(data,decision_times)
price_stat_ave_base =get_price_stat_ave(data_base,decision_times)

list_min,list_max = get_90_quantile(price_stat_ave)
plt.figure()
plt.plot(decision_times[:-1],list_min, 'r--')
plt.plot(decision_times[:-1],list_max,'r--')
plt.plot(decision_times[:-1],price_stat_ave_base[0,:],'b')
plt.title('Sensitivity Analysis for Variable theta1000', size ='xx-large')
plt.ylabel('Price in $', size = 'x-large')
plt.xlabel('Period Index', size = 'x-large')

plt.savefig('sensitivity_analysis_theta1000')
#plt.xlim(decision_times)

In [ ]:
plt.show()